# modified: 2026-02-28

tui: false # modern terminal UI with nice keybindings
agent: false # enable agent mode (more autonomous)
auto-commits: true
auto-save: true
cache-prompts: true
use-enhanced-map: true
watch-files: true
model_settings_file: .cecli.model.settings.yml

# OpenRouter models
#
model: openrouter/moonshotai/kimi-k2.5
#model: openrouter/z-ai/glm-5
#model: openrouter/minimax/minimax-m2.5
#model: openrouter/google/gemini-3-flash-preview
#model: openrouter/google/gemini-3.1-pro-preview

# ZenMux models
#
#model: gemini-3.1-pro-preview
#model: gemini-3-flash-preview
